# Generated by Django 4.2.5 on 2023-09-21 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=100, null=True, unique=True, verbose_name='username')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='apellidos')),
                ('fecha_nac', models.DateField(blank=True, null=True, verbose_name='fecha_nac')),
                ('dni', models.IntegerField(blank=True, null=True, unique=True, verbose_name='dni')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='direccion')),
                ('localidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='localidad')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='nacionalidad')),
                ('telefono_1', models.IntegerField(blank=True, null=True, verbose_name='telefono_1')),
                ('telefono_2', models.IntegerField(blank=True, null=True, verbose_name='telefono_2')),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado/a', 'Casado/a'), ('Soltero/a', 'Soltero/a'), ('Viudo/a', 'Viudo/a'), ('Divorciado/a', 'Divorciado/a')], max_length=50, null=True, verbose_name='estado_civil')),
                ('sexo', models.CharField(blank=True, choices=[('01', 'Masculino'), ('02', 'Femenino'), ('03', 'Otro')], max_length=2, null=True, verbose_name='sexo')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='imagenPerfil')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100, unique=True, verbose_name='nombre_carrera')),
                ('num_resolucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='num_resolucion')),
                ('duracion_carrera', models.PositiveBigIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_instituto', models.CharField(max_length=100, unique=True, verbose_name='nombre_instituto')),
                ('email_instituto', models.EmailField(max_length=254, unique=True, verbose_name='email_instituto')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('localidad', models.CharField(max_length=50, verbose_name='localidad')),
                ('ciudad', models.CharField(max_length=100, verbose_name='ciudad')),
                ('telefono_1', models.IntegerField(verbose_name='telefono_1')),
                ('telefono_2', models.IntegerField(verbose_name='telefono_2')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='imagenPerfil')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100, unique=True, verbose_name='nombre_materia')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.carrera')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios_carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreras', models.ManyToManyField(to='inscripcionFinales.carrera')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCorrelativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_correlativas', to='inscripcionFinales.materia')),
                ('materia_correlativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas_de', to='inscripcionFinales.materia')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='instituto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcionFinales.instituto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.ManyToManyField(blank=True, to='inscripcionFinales.carrera'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
