# Generated by Django 4.2.2 on 2023-09-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcionFinales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('01', 'Masculino'), ('02', 'Femenino'), ('03', 'Otro')], max_length=2, null=True, verbose_name='sexo'),
        ),
    ]
